### ISSUE TITLE
Success/Error or Warnings Design Widget

### ISSUE THREAD

**Issue by joemar25** [Quanby-IT-Solutions/PCIC-Mobile-App#142]
https://www.youtube.com/watch?v=UWXC0DHIIfQ

instead of using snackbar. use a flash message is better.
example:
![image](https://github.com/Quanby-IT-Solutions/PCIC-Mobile-App/assets/80235976/89393b06-9614-4d40-8401-5e2f3ea3fca4)

see the back button. here if error, we should make sure that it goes back to its previous page automatically.

**Comment by joemar25** [comment]
may use this:
https://www.youtube.com/watch?v=UWXC0DHIIfQ

or a plugin:
https://pub.dev/packages/flash

**Comment by socratat-b** [comment]
pa open na lang if may need pa papalitan
