### ISSUE TITLE
automatic folder syncing of csv to database

### ISSUE THREAD

**Issue by joemar25** [Quanby-IT-Solutions/PCIC-Mobile-App#64]
babasahin ung folder, titignan kung ano ung mga csv files na andun, if overall complete na sila wag na ilagay, if meron pa kunin lang ung task na unknown pa, para ilalagay sa db ung id's to keep track ung progress. if done or not.

**Comment by joemar25** [comment]
Dito pansamantala ilalagay natin ung mga uploaded csv files nila (FTP wannabe) then maga lagay ng sync button sa app to update the applications task and database.

**Comment by Lucheezou** [comment]
goodies na
